title       = "rxnorm"
baseURL     = "https://rxnorm-cli.tamnd.com/"
description = "A command line for the RxNorm drug terminology API."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/rxnorm-cli"
